name: Push to ghcr.io
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      packages: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: | 
            ghcr.io/pixelomer/reference-viewer:latest
            ghcr.io/pixelomer/reference-viewer:${{ github.run_number }}
          platforms: linux/amd64,linux/arm64
